### ISSUE TITLE
please support print level constants

### ISSUE THREAD

**Issue by plainOldCode** [KnowRe/swint-helper#1]
Cannot recognize when I see number 0,1,2,3,4 ... what is level.

how about these?

print(0, 'Raw message');
print(print.RAW, 'Raw message');
// ==> Raw message
print(1, 'Debug message');
print(print.DEBUG, 'DEBUG message');
// ==> DEBUG/2015-05-07T13:55:35.612Z)
//      Debug message
print(2, 'Info message');
print(print.INFO, 'INFO message');
// ==> INFO /2015-05-07T13:55:35.612Z)
//      Info message
print(3, 'Warning message');
print(print.WARNING, 'WARN message');
// ==> WARN /2015-05-07T13:55:35.612Z)
//      Warning message
print(4, 'Error message');
print(print.ERROR, 'ERROR message');
// ==> ERROR/2015-05-07T13:55:35.612Z)
//      Error message

**Comment by Kivol** [comment]
I think it's too complex, and there are quite a lot of code that use print like `print(4, err);`.
FYI, for example, just using `print(3)` actually prints `3`, which means one-value call is just printing with level 2.

**Comment by KnowRe** [comment]
Added `print.XXX` constant support in 1.1.0, commit 670e043ea72f64878a1c0a878d4f9c59221723c9.
